language: node_js
node_js:
  - stable
group: 
  - stable
dist: 
  - trusty
addons:
  sonarqube: true
  sonarcloud:
    organization: "madhusj-github"
    token:
      secure: 324f826878b7fc9db934d6319763335e22a08a80
script:
  - sonar-scanner 
