language : node_js
node_js:
  - stable
addons:
  sonarcloud:
    organization: "madhusj-github" # the key of the org you chose at step #3
    token:
      secure: 38647714262d9d9325aab1bc3e054cc51b478035

