language: node_js
node_js:
  - stable
addons:
  sonarcloud:
    organization: "madhusj-github"
    token:
      secure: "3bc17c99fc1b91b6e97c981cc0e73afce83c14a3"
script:
  - sonar-scanner
  - npm run build
  - npm test
